<a href="https://colab.research.google.com/github/theo3-hash/ML-Projects/blob/main/cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

# Models

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Data Collection & Processing

In [3]:
heart_data = pd.read_csv('/content/heart.csv')

In [7]:
heart_data.head()



age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [8]:
heart_data.shape

(1025, 14)

In [9]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# Features & Target splitting

In [10]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [11]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2  

# Train & Test data splitting

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [13]:
print(X.shape, X_train.shape, X_test.shape)

(1025, 13) (820, 13) (205, 13)


# Comparing different Model Performance

In [14]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()] # list of models

In [16]:
def compare_models_train_test():
  for model in models:

    # Training the model
    model.fit(X_train, Y_train)

    # Predicting from the model
    test_data_prediction = model.predict(X_test)
    accuracy = accuracy_score(Y_test, test_data_prediction)
    print('Accuracy score of the ', model, ' = ', accuracy)

In [17]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.8146341463414634
Accuracy score of the  SVC(kernel='linear')  =  0.824390243902439
Accuracy score of the  KNeighborsClassifier()  =  0.7219512195121951
Accuracy score of the  RandomForestClassifier()  =  1.0


# Cross Validation

Logistic Regression

In [21]:
cv_score_lr = cross_val_score(LogisticRegression(max_iter=10000), X, Y, cv=5)

print(cv_score_lr)

mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)

mean_accuracy_lr = mean_accuracy_lr*100

mean_accuracy_lr = round(mean_accuracy_lr, 2) # provide 2 deciman

print(mean_accuracy_lr)

[0.88292683 0.85853659 0.87804878 0.82439024 0.80487805]
84.98


Support Vector Machine

In [22]:
cv_score_svc = cross_val_score(SVC(kernel='linear'), X, Y, cv=5)

print(cv_score_svc)

mean_accuracy_svc = sum(cv_score_svc)/len(cv_score_svc)

mean_accuracy_svc = mean_accuracy_svc*100

mean_accuracy_svc = round(mean_accuracy_svc, 2) # provide 2 deciman

print(mean_accuracy_svc)

[0.88292683 0.86829268 0.84390244 0.81463415 0.80487805]
84.29


K-Nearest Classifier

In [23]:
cv_score_knn = cross_val_score(KNeighborsClassifier(), X, Y, cv=5)

print(cv_score_knn)

mean_accuracy_knn = sum(cv_score_knn)/len(cv_score_knn)

mean_accuracy_knn = mean_accuracy_knn*100

mean_accuracy_knn = round(mean_accuracy_knn, 2) # provide 2 deciman

print(mean_accuracy_knn)

[0.76585366 0.74634146 0.76097561 0.71219512 0.75121951]
74.73


Random Forest Classifier

In [24]:
cv_score_rfc = cross_val_score(RandomForestClassifier(), X, Y, cv=5)

print(cv_score_rfc)

mean_accuracy_rfc = sum(cv_score_rfc)/len(cv_score_rfc)

mean_accuracy_rfc = mean_accuracy_rfc*100

mean_accuracy_rfc = round(mean_accuracy_rfc, 2) # provide 2 deciman

print(mean_accuracy_rfc)

[1.         1.         0.98536585 1.         0.98536585]
99.41


# Creating a function to compare the models

In [25]:
# List of models
models_list = [LogisticRegression(max_iter=10000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [26]:
def compare_models_cross_validation():
  for model in models_list:

    cv_score = cross_val_score(model, X, Y, cv=5)

    mean_accuracy = sum(cv_score)/len(cv_score)

    mean_accuracy = mean_accuracy*100

    mean_accuracy = round(mean_accuracy, 2) # for 2 decimal number

    print('Cross Validation accuracies for the ', model, ' = ', cv_score)

    print('Accuracy % of the ', model, ' = ', mean_accuracy)

    print('----------------------------------------------------------------------------------------------------------------')

In [27]:
compare_models_cross_validation()

Cross Validation accuracies for the  LogisticRegression(max_iter=10000)  =  [0.88292683 0.85853659 0.87804878 0.82439024 0.80487805]
Accuracy % of the  LogisticRegression(max_iter=10000)  =  84.98
----------------------------------------------------------------------------------------------------------------
Cross Validation accuracies for the  SVC(kernel='linear')  =  [0.88292683 0.86829268 0.84390244 0.81463415 0.80487805]
Accuracy % of the  SVC(kernel='linear')  =  84.29
----------------------------------------------------------------------------------------------------------------
Cross Validation accuracies for the  KNeighborsClassifier()  =  [0.76585366 0.74634146 0.76097561 0.71219512 0.75121951]
Accuracy % of the  KNeighborsClassifier()  =  74.73
----------------------------------------------------------------------------------------------------------------
Cross Validation accuracies for the  RandomForestClassifier()  =  [1.         1.         1.         0.98536585 0.98536585]